### ISSUE TITLE
Gnome 40 support

### ISSUE THREAD

**Issue by gaborbernat** [hedayaty/NetSpeed#127]
Seems the extension works, but accessing the preferences page crashes with:

```
TypeError: this.main.show_all is not a function

Stack trace:
  NetSpeed_App@/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js:287:19
  buildPrefsWidget@/usr/share/gnome-shell/extensions/netspeed@hedayaty.gmail.com/prefs.js:293:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
```

**Comment by tobecci** [comment]
please, can the devs look into this GNOME 40 compatibility issue, will be appreciated

**Comment by hedayaty** [comment]
Done.
I will update it to gnome as well not sure how long it will take them to review :(

**Comment by guihkx** [comment]
Can you keep this open until a GNOME 40-compatible version is available on the GNOME Extensions website? Thank you!

**Comment by zhanghai** [comment]
Hi Amir,

First of all thank you for the extension!

It has been 25 days since your last comment and the extension on https://extensions.gnome.org/extension/104/netspeed/ still isn't showing a 40 version. I'm also a extension developer myself and my last extension update to add the shell version 40 was instantly auto approved, probably because it's just a manifest update. So I was wondering if you have uploaded the new version to the GNOME Extensions website, and if so, was there any blocker for it to become public?

**Comment by nlpsuge** [comment]
@hedayaty 

This gnome 40 supported extension does not appear https://extensions.gnome.org/extension/104/netspeed/, can you please check it out?

**Comment by hedayaty** [comment]
Sorry guys!
These days are harder to work on the extension.
We do not get much support from gnome. Also using work laptop, switching to my linux box is more rare to work on the extension.
I was adding the placement. Finally, made it work.
Submitted the extension for gnome.
I wish I just submitted the small change with gnome-40 support first then these ones.

**Comment by c84c** [comment]
Hi all,

I installed extension through package manager and the extension **work like a charm**!

I hope this can be useful.

I'm on Fedora 34 and I use `dnf` to install it:
```bash
$ dnf install gnome-shell-extension-netspeed
```

This is my setup:
```bash
$ cat /etc/fedora-release
Fedora release 34 (Thirty Four)
```

```bash
$ gnome-shell --version
GNOME Shell 40.2
```

```bash
$ gjs --version
gjs 1.68.1
```

**Comment by hedayaty** [comment]
I think it is active on gnome
